#!/usr/bin/env python3
"""
Generates the 1200x630 Open Graph share card for every page.

    python3 tools/build_og_images.py

Titles come from content/pages.json, the same file that feeds <title>, so a
card can never advertise something different from the page it links to.

Why generated rather than hand-made in a design tool: there are nine pages and
there will be more. A hand-made set goes stale the first time a title changes,
silently, because nobody re-exports a PNG when they edit a heading.

The cards ARE guarded, but not by re-rendering them. PNG encoding is not
byte-stable across Pillow and libpng versions, so a regenerated file can differ
with no content change, and CI would fail on an upgrade rather than on a real
problem. Re-rendering in CI is also disproportionate: it needs Python, Pillow,
a libcairo build and the IBM Plex fonts, none of which this Node-only pipeline
otherwise carries, and the fonts are not in the repo.

So this script emits assets/og/manifest.json recording the exact title and
description each card was rendered FROM, plus the file's sha256, and
tools/test_og_cards.cjs asserts in CI that the manifest still matches
content/pages.json. Changing a title without re-running this script leaves the
manifest stale and goes red — which is the failure that actually happened:
ai-readiness.png advertised "twelve-question ... six areas" for the whole life
of a sixteen-question, eight-area instrument, live, with every other check
green. Nothing could see it, because this was the one artifact in the pipeline
with no guard at all.

⚠️ The manifest is a GENERATED artifact and must be regenerated by running this
script, never hand-edited to make CI green. Editing it to match pages.json
without re-rendering reproduces exactly the drift it exists to catch.

The existing favicons are unsuitable as share images: every one is square
(ratio 1.0, largest 512x512) against Open Graph's 1.91 target, so platforms
either pillarbox them with grey bars or centre-crop the logo, and below 1200px
wide LinkedIn falls back to a small thumbnail card instead of the large one.
"""

import hashlib
import json
import os
import re
import sys
from pathlib import Path

import cairosvg
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
PAGES = ROOT / "content" / "pages.json"
LOGO = ROOT / "assets" / "vestibular_logo.svg"
OUT_DIR = ROOT / "assets" / "og"
MANIFEST = OUT_DIR / "manifest.json"
PRACTICES = ROOT / "content" / "practices.json"

# Phrase separator in a card title. Spaced so it cannot match a hyphenated word
# ("AI-Transformational" must not become two phrases).
SEPARATOR = " - "
FONT_DIR = Path(os.environ.get("VN_FONT_DIR", "/tmp"))

W, H = 1200, 630                 # Open Graph large-card canvas
BG = (0, 0, 0)                   # --background-color
LIME = (152, 203, 43)            # --primary-color  hsla(79,65%,48%,1)
TEXT = (255, 255, 255)           # --hero-text-color
MUTED = (224, 224, 224)          # --body-text-color


def load_font(name: str, size: int) -> ImageFont.FreeTypeFont:
    path = FONT_DIR / name
    if not path.exists():
        sys.exit(
            f"FAIL: font not found at {path}\n"
            f"Fetch IBM Plex Sans (Bold + Regular) into {FONT_DIR}, or set "
            f"VN_FONT_DIR to where they live."
        )
    return ImageFont.truetype(str(path), size)


def wrap(draw: ImageDraw.ImageDraw, text: str, font, max_w: int) -> list[str]:
    """Greedy wrap measured against the real font, not an estimated char count."""
    words, lines, cur = text.split(), [], ""
    for word in words:
        trial = f"{cur} {word}".strip()
        if draw.textlength(trial, font=font) <= max_w:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


def title_lines_for(page: str, draw, font, max_w: int, cap: int) -> list[str]:
    """A title written as separated phrases breaks at its SEPARATORS, not
    wherever the greedy wrapper runs out of pixels.

    'Fix your framework - Flex AI - Free your humans' wrapped greedily into
    'Fix your framework - Flex' / 'AI - Free your humans', splitting a phrase
    across the break so it read as a typo. Phrases are the unit here.

    A phrase too wide for one line still falls back to greedy wrapping rather
    than overflowing the canvas, and the cap applies to the total either way.
    """
    parts = [seg.strip() for seg in page.split(SEPARATOR)] if SEPARATOR in page else [page]
    lines: list[str] = []
    for part in parts:
        lines.extend(wrap(draw, part, font, max_w))
    if len(lines) > cap:
        sys.exit(
            f"FAIL: title needs {len(lines)} lines, cap is {cap}.\n"
            f"  title:   {page!r}\n"
            f"  dropped: {lines[cap:]!r}\n"
            f"  Shorten it, or give it fewer phrases."
        )
    return lines


def split_title(title: str) -> tuple[str, str]:
    """Titles read 'Vestibular AI Transformation - Playbook'. The part after the
    dash is the page; the part before is the brand line above it."""
    if "\u2013" in title:
        brand, page = title.split("\u2013", 1)
        return brand.strip(), page.strip()
    return "Vestibular", title.replace("Vestibular", "").strip() or title.strip()


def build_card(page_file: str, title: str, description: str, logo: Image.Image) -> Image.Image:
    card = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(card)

    # Lime rule along the top, echoing the hero band.
    draw.rectangle([0, 0, W, 10], fill=LIME)

    logo_size = 230
    x = 72 + logo_size + 60
    max_w = W - x - 72

    f_brand = load_font("IBMPlexSans-Regular.ttf", 30)
    f_title = load_font("IBMPlexSans-Bold.ttf", 62)
    f_desc = load_font("IBMPlexSans-Regular.ttf", 27)

    brand, page = split_title(title)
    title_lines = title_lines_for(page, draw, f_title, max_w, cap=3)
    desc_lines = wrap(draw, description, f_desc, max_w)

    # ⛔ OVERFLOW IS A FAILURE, NOT A TRUNCATION. Both of these used to be
    # sliced — wrap(...)[:2] and wrap(...)[:3] — so a description one clause too
    # long lost its tail with no ellipsis and no warning, and the card rendered
    # happily. The 155-character trim above does NOT cover this: it counts
    # characters while the cap counts rendered lines, and a measured
    # 89-character string in wide glyphs still wraps to four.
    if len(desc_lines) > 3:
        sys.exit(
            f"FAIL: {page_file} description needs {len(desc_lines)} lines, cap is 3.\n"
            f"  drawn text: {description!r}\n"
            f"  dropped:    {desc_lines[3:]!r}\n"
            f"  Shorten content/pages.json's description for this page."
        )

    # Measure the block, then centre it. Cards have between one and two title
    # lines and one to three description lines, so a fixed offset leaves the
    # short ones hanging off the top of a mostly empty canvas.
    # The gap under the title is 14px, tuned when a title could be at most two
    # lines. A stacked three-line triplet crowds the description at that value.
    # Widened ONLY for the tall case: a flat 28px would restyle all eleven cards
    # to fix one, and the other ten were not asked to move.
    title_gap = 28 if len(title_lines) >= 3 else 14
    block_h = 44 + len(title_lines) * 74 + title_gap - 14 + 18 + len(desc_lines) * 40
    y = (H - block_h) // 2

    draw.text((x, y), brand.upper(), font=f_brand, fill=LIME)
    y += 52
    for line in title_lines:
        draw.text((x, y), line, font=f_title, fill=TEXT)
        y += 74
    y += title_gap
    for line in desc_lines:
        draw.text((x, y), line, font=f_desc, fill=MUTED)
        y += 40

    lg = logo.resize((logo_size, logo_size), Image.LANCZOS)
    card.paste(lg, (72, (H - logo_size) // 2 - 10), lg)

    draw.text((72, H - 68), "vestibular.nexus", font=f_desc, fill=LIME)
    return card


def card_source(page_file: str, meta: dict, hero: dict) -> tuple[str, str, dict]:
    """Where a card's words come from, and the record of it for the manifest.

    Most cards take the page's own <title> and meta description, which is what
    keeps a card from advertising something the page does not say.

    index.html is the exception, deliberately. Its <title> has to carry the
    brand for a search result — "Vestibular Agile & AI Transformation" — while
    the card is the one surface where the brand's own voice belongs. Those are
    different jobs and one string cannot do both well.

    ⚠️ THE EXCEPTION IS A DERIVATION, NOT A SECOND COPY. The root card's words
    ARE the hero's words, transformed here and stored nowhere. Adding a
    hand-written card_title field to pages.json instead would put the same
    sentence in two files with nothing holding them together — which is exactly
    how ai-readiness.png came to advertise an instrument that no longer existed.

    Returns (title, description, source_record). The source record names the
    file and path the values came from and carries the values verbatim, so
    tools/test_og_cards.cjs can verify they have not moved WITHOUT having to
    reimplement this transformation in another language.

    ⚠️ `path` is a LIST of keys, never a dotted string. Page keys are filenames
    and contain dots, so "pages.services.html" splits into three keys and
    resolves to nothing — caught the first time this ran over real data.
    """
    if page_file == "index.html":
        return (
            SEPARATOR.join(line.rstrip(".") for line in hero["headline"]),
            hero["lede"],
            {
                "file": "content/practices.json",
                "path": ["brand", "hero"],
                "values": {"headline": hero["headline"], "lede": hero["lede"]},
            },
        )

    return (
        meta["title"],
        meta["description"],
        {
            "file": "content/pages.json",
            "path": ["pages", page_file],
            "values": {"title": meta["title"], "description": meta["description"]},
        },
    )


def main() -> None:
    if not PAGES.exists():
        sys.exit(f"FAIL: {PAGES} not found")
    pages = json.loads(PAGES.read_text())["pages"]
    hero = json.loads(PRACTICES.read_text())["brand"]["hero"]

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Strip the wordmark <text> elements before rasterising: they are filled
    # #182a04 on a #182904 stroke, which vanishes against this card's black
    # background. The mark alone carries the brand, and the footer wordmark
    # below states the domain in lime.
    svg = LOGO.read_text()
    mark_only = re.sub(r"<text\b.*?</text>", "", svg, flags=re.S)
    png = cairosvg.svg2png(bytestring=mark_only.encode(), output_width=420, output_height=420)
    logo = Image.open(__import__("io").BytesIO(png)).convert("RGBA")

    manifest_cards = {}

    for page_file, meta in pages.items():
        title, desc, source = card_source(page_file, meta, hero)
        # The description is written for search results and runs long. Trim at
        # a WORD boundary, never at punctuation: these descriptions lead with a
        # label ending in a colon, so splitting on punctuation left a fragment.
        short = desc if len(desc) <= 155 else desc[:155].rsplit(" ", 1)[0].rstrip(" ,;:") + "\u2026"

        card = build_card(page_file, title, short, logo)
        out = OUT_DIR / f"{Path(page_file).stem}.png"
        card.save(out, "PNG", optimize=True)

        # `title`/`description` are what was DRAWN and are informational. The
        # check reads `source`, because that is what can go stale.
        manifest_cards[page_file] = {
            "title": title,
            "description": desc,
            "source": source,
            "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        }
        print(f"  {out.relative_to(ROOT)}  {out.stat().st_size:,} B")

    MANIFEST.write_text(
        json.dumps(
            {
                "_comment": (
                    "GENERATED by tools/build_og_images.py — do not hand-edit. "
                    "Records the content/pages.json strings each card was rendered "
                    "from, so tools/test_og_cards.cjs can detect a title that moved "
                    "without the card being re-rendered."
                ),
                "cards": manifest_cards,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"\nrendered {len(pages)} card(s) at {W}x{H}")
    print(f"wrote {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
